--SYSTEM
alter session set "_ORACLE_SCRIPT"=true;
create user STATEMENT
identified by STATEMENT
default tablespace USERS;



--STATEMENT
CREATE TABLE tutorials (
  id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR2(255),
  description VARCHAR2(255),
  published NUMBER(1) DEFAULT 0,
  PRIMARY KEY(id)
);