--SYSTEM
alter session set "_ORACLE_SCRIPT"=true;
create user STATEMENT
identified by STATEMENT
default tablespace USERS;



--STATEMENT
create TABLE tutorials (
  id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR2(255),
  description VARCHAR2(255),
  published NUMBER(1) DEFAULT 0,
  PRIMARY KEY(id)
);


--Author
 create TABLE "STATEMENT"."AUTHOR"
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START with 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"NAME" VARCHAR2(255 BYTE),
	"TITLE" VARCHAR2(255 BYTE),
	"BRIEF_PROFILE"  VARCHAR2(4000 BYTE) DEFAULT 0,

	 PRIMARY KEY ("ID")

   );



--DML
--CRUD

INSERT INTO AUTHOR (name,TITLE,brief_profile)VALUES('SH','Dr','Professor');
SELECT * from Author where name = 'SH';
UPDATE author set title ='Dr.' where name = 'SH';
DELETE from author   where name = 'SH';


truncate TABLE author;

--DDL
create table Price
(id VARCHAR2(3 CHAR),
cost number(10));

create or REPLACE VIEW V_STATEMENT AS (SELECT * FROM customer_statement);

drop table author;