INSERT INTO AUTHOR (id,NAME, TITLE, BRIEF_PROFILE, PUBLISHYEAR) VALUES (1,'APJ', 'Dr.', 'President of India', '2007');
INSERT INTO AUTHOR (id,NAME, TITLE, BRIEF_PROFILE, PUBLISHYEAR) VALUES (2,'Gandhi', 'Dr.', 'Cool man', '2005');
INSERT INTO AUTHOR (id,NAME, TITLE, BRIEF_PROFILE, PUBLISHYEAR) VALUES (3,'PK', 'Dr.', 'Demi god', '2003');