INSERT INTO AUTHOR (id,NAME, TITLE, BRIEF_PROFILE) VALUES (1,'APJ', 'Dr.', 'President of India');
INSERT INTO AUTHOR (id,NAME, TITLE, BRIEF_PROFILE) VALUES (1,'Gandhi', 'Dr.', 'Cool man');
INSERT INTO AUTHOR (id,NAME, TITLE, BRIEF_PROFILE) VALUES (1,'PK', 'Dr.', 'Demi god');